<?php

namespace NextDeveloper\Agenda\Services;

use App\Models\User;
use NextDeveloper\Agenda\Services\AbstractServices\AbstractCalendarItemsService;
use NextDeveloper\IAM\Database\Models\Users;
use NextDeveloper\IAM\Helpers\UserHelper;

/**
 * This class is responsible from managing the data for CalendarItems
 *
 * Class CalendarItemsService.
 *
 * @package NextDeveloper\Agenda\Database\Models
 */
class CalendarItemsService extends AbstractCalendarItemsService
{

    // EDIT AFTER HERE - WARNING: ABOVE THIS LINE MAY BE REGENERATED AND YOU MAY LOSE CODE

    public static function create(array $data)
    {
        if(array_key_exists('guests', $data)) {
            foreach ($data['guests'] as $key => $guest) {
                $data['guests'][$key] = Users::where('uuid', $guest)->first()->id;
            }
        }

        return parent::create($data); // TODO: Change the autogenerated stub
    }
}
